name: ai-school

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Run Larastan for Static Analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G
  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $SERVER_USER@$SERVER_IP << 'EOF'
            cd /var/www/school/backend

            # Pull the latest changes from the main branch
            if [ ! -d ".git" ]; then
                git clone https://github.com/hosseinmirzapur/ai-school-backend.git . || exit 1
              else
                git stash
                git pull origin main
                git stash pop
              fi

            # Copy .env to the project directory
            cp /var/www/school/.env /var/www/school/backend/

            php8.2 /usr/local/bin/composer install --no-dev --optimize-autoloader

            # Set directory permissions for storage and cache
            sudo chmod -R 777 storage bootstrap/cache

            # Optimize the app
            php8.2 artisan migrate --force
            php8.2 artisan config:cache
            php8.2 artisan route:cache
            php8.2 artisan filament:optimize

            # Restart php-fpm to apply changes
            sudo systemctl restart php8.2-fpm
          EOF

          # Clean up the temporary key file
          rm -f private_key
